### ISSUE TITLE
Breadcrumb function override

### ISSUE THREAD

**Issue by robhuijben** [EmicoEcommerce/Magento2AttributeLandingTweakwise-archived#5]
In `src/Block/Catalog/Breadcrumbs.php` the protected function `_prepareLayout` creates the breadcrumb path, but it looks at the complete URL path for a crumb, instead of splitting them in to separate crumbs. Looking at the code, the crumb path can exist of three levels maximum, which could also be more if categories are included.

Can you make this a public function instead, so it can be extended / overridden and extra levels can be applied?

**Comment by edwinljacobs** [comment]
Hi,

Will this do? https://github.com/EmicoEcommerce/Magento2AttributeLanding/blob/issue/5-override-breadcrumbs/src/Block/Catalog/Breadcrumbs.php

If so ill merge and tag it.

With kind regards

**Comment by edwinljacobs** [comment]
Judging by your description, your aim is to include the category path of the landing page as breadcrumb?

so if your landingpage is based on category "t-shirts" and has filter color = red you would expect the following breadcrumbs 'clothing' > 'men' > 't-shirts' > 'red-t-shirts' (here red-t-shirts is the landing page)?

**Comment by robhuijben** [comment]
> Judging by your description, your aim is to include the category path of the landing page as breadcrumb?
> 
> so if your landingpage is based on category "t-shirts" and has filter color = red you would expect the following breadcrumbs 'clothing' > 'men' > 't-shirts' > 'red-t-shirts' (here red-t-shirts is the landing page)?

That would be correct. It would even be better if you have to choice to include category in the breadcrumbs or not, but if that's too much work the solution you give above is alright. Thanks for thinking along with me.

**Comment by edwinljacobs** [comment]
For now I merged the fix and created release: https://github.com/EmicoEcommerce/Magento2AttributeLanding/releases/tag/v1.0.2

Perhaps it is best to make an option for this on the landingpage however that would take more effort and testing (the root category can also be selected as base category for the landing page, perhaps this causes issues).

For now making the breadcrumb logic public suffices.
